### ISSUE TITLE
Support for Quanser Q2-USB

### ISSUE THREAD

**Issue by MarkusLohmayer** [quanser/hil_sdk_linux_x86_64#1]
Dear Support,

it would be very helpful if you could support the Q2 Hardware with this SDK.

**Comment by hlacheray** [comment]
Hello @MarkusLohmayer ,

Thank you for the feature request. We'll take your feedback into account for our development roadmap. Currently, the Quanser Q2-USB is fully supported in our HIL SDK for 64-bit Windows:
https://github.com/quanser/hil_sdk_win64

Regards,
